name: Check for Merge request

on:
  pull_request:
    branches: [ master ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Check homework for lesson1
      run: ./gradlew lesson1:check
    - name: Check homework for lesson6
      run: ./gradlew lesson6:check
